---

- name: Get current block height
  ansible.builtin.command: dash-cli getblockcount
  register: blocks_count
  changed_when: blocks_count | int != 0

- name: Activate DML by generating blocks up to height {{ spork_ready_block_height }}
  ansible.builtin.include_role:
    name: generate_blocks
  vars:
    generate: blocks
    num_blocks: "{{ spork_ready_block_height - (blocks_count.stdout | int) }}"
  when: (blocks_count.stdout | int) < spork_ready_block_height

- name: Get active sporks list
  ansible.builtin.command: dash-cli spork active
  register: active_sporks
  changed_when: active_sporks | length > 0

- name: Process active sporks list
  ansible.builtin.set_fact:
    active_sporks_list: '{{ (active_sporks_list | default([])) + [item.key] }}'
  when: item.value
  with_dict: '{{ active_sporks.stdout | from_json }}'

- name: Prepare target sporks list
  ansible.builtin.set_fact:
    target_sporks: '{{ (target_sporks | default([])) + [item.key] }}'
  when: item.value
  with_dict: '{{ sporks }}'

- name: Prepare list of sporks to be activated
  ansible.builtin.set_fact:
    activate_sporks: '{{ target_sporks | difference(active_sporks_list) }}'

- name: Activate non active sporks
  ansible.builtin.command: dash-cli sporkupdate {{ item }} 0
  with_items: '{{ activate_sporks }}'
