---

- name: Create Insight dir
  ansible.builtin.file:
    path: '{{ insight_path }}'
    state: directory
    recurse: true

- name: Copy files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ insight_path }}/{{ item }}'
    mode: "0644"
  loop:
    - docker-compose.yml
    - dashcore-node.json
    - insight-proxy-nginx.conf
    - .env

- name: Start Insight
  community.docker.docker_compose_v2:
    project_src: '{{ insight_path }}'
    state: present
    pull: always
    recreate: always
  register: output

- name: Check Insight container
  ansible.builtin.assert:
    that:
      - output.containers is defined
      - (output.containers | selectattr('Service', '==', 'insight') | list) | length > 0
      - (output.containers | selectattr('Service', '==', 'insight') | list)[0].State == 'running'
    fail_msg: "No 'insight' container found or it isn't running."

- name: Check Insight Proxy container
  ansible.builtin.assert:
    that:
      - output.containers is defined
      - (output.containers | selectattr('Service', '==', 'insight_proxy') | list) | length > 0
      - (output.containers | selectattr('Service', '==', 'insight_proxy') | list)[0].State == 'running'
    fail_msg: "No 'insight proxy' container found or it isn't running."
