- name: create insight dir
  file: path='{{ insight_path }}' state=directory recurse=true

- name: copy insight docker compose
  template:
    src: '{{ item }}.j2'
    dest: '{{ insight_path }}/{{ item }}'
  loop:
  - docker-compose.yml
  - dashcore-node.json
  - .env

- name: start insight
  docker_service:
    project_src: '{{ insight_path }}'
    state: present
    restarted: yes
    pull: yes

- name: check Insight container
  assert:
    that: 'insight.{{ insight_compose_project_name }}_insight_1.state.running'
