---

- name: Create Insight dir
  file:
    path: '{{ insight_path }}'
    state: directory
    recurse: true

- name: Copy files
  template:
    src: '{{ item }}.j2'
    dest: '{{ insight_path }}/{{ item }}'
    mode: 0644
  loop:
    - docker-compose.yml
    - dashcore-node.json
    - insight-proxy-nginx.conf
    - .env

- name: Start Insight
  docker_compose:
    project_src: '{{ insight_path }}'
    state: present
    restarted: true
    pull: true
  register: output

- name: Check Insight container
  assert:
    that: 'output.services.insight.insight.state.running'

- name: Check Insight Proxy container
  assert:
    that: 'output.services.insight_proxy.insight_proxy.state.running'
