---

# Requires "masternode" and "masternode_name" variables

- name: copy script
  copy:
    src: scripts/find-collateral.py
    dest: /usr/local/bin/find-collateral.py
    owner: root
    group: root
    mode: 0755

- name: find-collateral for {{ masternode_name }}/{{ masternode.collateral.address }}
  shell: find-collateral.py "{{ masternode_wallet_rpc_args }}" "{{ masternode.collateral.address }}" "{{ find_protx }}"
  register: r
  failed_when: False

- name: update collateral_ok
  ansible.builtin.set_fact:
    collateral_ok: '{{ r.rc == 0 }}'
    collateral_txid: ''
    collateral_vout: -1

- name: update txid/vout
  ansible.builtin.set_fact:
    collateral_txid: '{{ r.stdout_lines[0] }}'
    collateral_vout: '{{ r.stdout_lines[1] | int }}'
  when: collateral_ok

# Wow does this work?
- name: setting global masternode facts
  ansible.builtin.set_fact:
    collateral_ok_{{masternode_name | replace("-","_")}}: "{{ collateral_ok }}"
    collateral_txid_{{masternode_name | replace("-","_")}}: "{{ collateral_txid }}"
    collateral_vout_{{masternode_name | replace("-","_")}}: "{{ collateral_vout }}"

- ansible.builtin.debug:
    msg: "mn={{ masternode_name }} address={{ masternode.collateral.address }} collateral_ok={{collateral_ok}}, collateral_txid={{collateral_txid}}, collateral_vout={{collateral_vout}}"

- name: updating collateral_ok_count
  ansible.builtin.set_fact:
    collateral_ok_count: "{{ collateral_ok_count | int + 1 }}"
  when: collateral_ok
