sudo: required
dist: trusty

env:
  global:
    # DOCKER_HUB_USER
    - secure: "MD2Ik5fGbzoWejqdmJVwEnKRdbNHqVCzTDWq1cprTuCjWL9jcUL0CxsvWLA9ZeShu95Wddz4j2hMCVo4wc0px7qglNpf97YBllK2LesQUdMm79ArNwASYVsONZ2Sm2DZ5142HKKREcUsp0fm31FhFw1HVPDT69zgQXjXxQrTBXf8f9qH5mF6FNB2mnQhhW+Tq09WchCZReWpD66M8cvWp610u58xGy3ZeYHAR+7GRdFaB8m1HfQIhZqvUINV7g+SNaPQGr8BV4kk2E8SmI26ImK2a2isWisuUCP3IRNfUbeqZH6aQnZKUs9ZE87RO7mb2YvVqS6eXlTHBrLi6/AZ170qeYjKbvfiYNwqd4zAkoRC1+N8XY2RBZageZTNP4OuoM2kB9yYmzNsoI7cLN4kSIyAOSh6C/Ja60xp4I+/bgS5IiLSjPxAHGia5iuUufYEwgJEf+QIUqD6Fr7geNry03TeLBiAmXNG3wlO0mK4aeY6wdctab+k/1kldlnCeT64vhqQ7j1whFq9G+MVh+aPe7747QmlOsKOsqUcsPxiWH1dkBd8QE/yUek555EOUknZOjiSfkHN2eAiy7+u09uEgD+uPRVvgnSx5MNSAg61bOW7h2MP9az+8HCItD0xgGxuk22DZQUXZ2E+oFMsLzR/yMxb7IJQKzACZYF2dC7cFFc="
    # DOCKER_HUB_PASSWORD
    - secure: "WruQkhJZ25ckLQwf9MKpUSBLVjshVlYgUbYKuX7OXNC8pRF4S8olLZKny6I582MIKMvvpbwIibwYgKBP1V3K8onGS7UCNvtuFfl0e5DXAtjEifV2kqogs+3UVC8nXQnOpAOBlk4LnVY1hcPX9kr/nfzdl00D6RykOySgFS5I3nI6yda+Yodu/xNPNq0Oh+reQ7DXOUPq4ZsRKe4Sj5YfGFLWk/1d3D+Wygzy7JSmW4kiRIpUOEWpteM4C+fSSVl5PNDisWhWmviVzRl8e5fKIe8XrfHzF++npwfJpsSz0EihqDnb2k/t+YohxatCd5JrZUgNdnXT5NBqdtjsi2X3+WyS9MG4i3Fppbtan2Nbbr2z+l40Fi1hZEZvmqVfeyi4sUZus16VEpAvB3z+bl8qAMIxEclgjsxn21WX2HrRexUQr0k+U0MzFet1HUe/Q0wPnuHsM4RBGuIlKlYcFxdh8hOZqtQl4Qf20rmzZXg7ij3Ikd3h71fvsyw6JYLcQtHhr935K3X7O/JABXuSjS91Fo6hEMEix5zsR015dFfJCNbmPLrjaruTzTxaiJplNI+43TcjL+4XSyZzuQI867SQPtJlW6ygcv1oxIeWrswDY/UMQ6miVV4vmGvO6kI+E7/GcbYyPcQCtnFr1ocu8SZcJQckvvfcQLTYjPN1Lme7x7Q="

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script: true

before_deploy:
  - docker build -t dashpay/dash-network-deploy . || travis_terminate 1
  - echo "$DOCKER_HUB_USER" | docker login -u "$DOCKER_HUB_USER" --password-stdin

deploy:
  provider: script
  script: docker push dashpay/dash-network-deploy
  on:
    branch: docker
