sudo: required
dist: trusty

env:
  global:
    # DOCKER_HUB_USER
    - secure: "BdLFI76RGFZ9W4GANYztz68hakyQGPFqahi8npQ0U8sVgg30RFUbg74TrWR6SKfOwjVMBg6a98cG/xXWY6c6ccWbf2rlYZz1ZJnzQ4yGZdllbPgrdQfSEz/dppv3tBjMe7TtR8RJb84VslT5e47fDdOTZfoucuyA/p2uZRA1A0NescJ+3ojVEUCpM8sBLUpM4y5cHCMw9ej3QtV4x8tZYczLUPHgFUs5jlfbTxgBPKcSITgNzS2tmXgj3VIZc/9hLmFKEF29uoPibxA970/9aSHxeKhBvONmgPkYLj8w/thFWtI3+K3LYOLnIW/3H+VfOHGfP/iytxzNvfAlGGQiRbvurnpVFrSDhwS1PJWmqgAL2zZAffh7IRa/Y4FgX8/rUbz5Mme6t86jJy+z6L/2QXvq72nT0QN1eeAs7UZFTUw5eOt20Kb04tntxf73PfrO15GGbVo2CRP0e9xbZvsybv7xwj8tckaxEGDS0k0QO7hI/UJf15GQy49aH2q2Wg2YXqT5AiR1c8FJd4cjus76vrDHyOlUhM6M+a1EnIgWXPGCZbx/zOgB1JwGNQPVWAvPOIVrnRvX1T1sFVHJZ5DM/L8qKrrW+66grstNXF+qC2PryciHvNy0Pg+KwxDPRfspdPGjXtigpe5E5cCrGGTNVEfkncPaVv6078kzF8JFUsQ="
    # DOCKER_HUB_PASSWORD
    - secure: "Knj3kCYvMxTXGPaWmd5j49ws5LtUt/QYtQpaVbRVNjAMOGDE6lis/sbSxz53cre7z33Gl5sy6/bcU7/lhb6NlH3mm9HRQ9r4gXdbdNLrQMVVavwqWCdtW5oQh3VnCZM3D6L7JQHhex02k+b2ymPnOlijfDMIntuXiCNQH5vchZVq53sRfRhwvUP8KQgRia+sFysn2AHiSfhZ8Z3+EDoDKzZ41tWLfN/Ai9nc0GAtI3QGI/xzKzcaVSbA+Rr1DNCaGSyPsXJnEo7rj0+S57t/NTgOTTQzkPPmNl4T1yM4oFfYphiF0ryt5EEqrZISLrlBoFlrcOnBkpSPLelJlxeg/tKwr4mfLjEHozww8NUUVVMfQWxEr1gF42kWDxQjI7dsuxg0v+FSL0CejI6oECSwJWNDdZu3DN2opAPkKRrwJpbNBdOqYpXDmECrzQp52huaWd4PpyBMIMEEbxS45kqvFSoC+GILAiivuFswxkEQ82yqlXBOaWwuVQ/Dk0apuiqmo4TOA+Ljmxm/PmznxK8lc5fXsUma014cF8ff+kVrgex6FPagCxqgJ541+UIDidhCpZUaulMTtRPOIA1dmfsgE3Q7nUeDu/WC+vf5KsOU3PUmurpyfdsWVT9hCZgcAgGfKgQJS3BBp3XxOyJBt9q1KhoGyg7ggDCJfhaRipDNTis="

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script: true

before_deploy:
  - docker build -t dashpay/dash-network-deploy . || travis_terminate 1
  - echo "$DOCKER_HUB_USER" | docker login -u "$DOCKER_HUB_USER" --password-stdin

deploy:
  provider: script
  script: docker push dashpay/dash-network-deploy
  on:
    branch: docker
