---

- name: get core container id
  command: docker ps -aqf "name=dashd"
  register: core_container_id

- name: get tenderdash container id
  command: docker ps -aqf "name=mn_evo_services_tendermint"
  register: tenderdash_container_id

- include_vars:
    file: common.yml

- include_vars:
    file: core.yml
    name: beat_conf

- include_vars:
    file: platform.yml
    name: platform_beat_conf
  when: tenderdash_container_id.stdout != ""

- set_fact:
    beat_conf: "{{ [beat_conf, platform_beat_conf] | combine(recursive=True, list_merge='append') }}"
  when: tenderdash_container_id.stdout != ""

- name: set up filebeat log monitoring
  include_role:
    name: geerlingguy.filebeat
