---

- name: copy filebeat ILM policy
  template:
    src: 'ilm_policy.json.j2'
    dest: '/etc/filebeat/ilm_policy.json'
    mode: 0644
    owner: root
    group: root

- name: set up filebeat log monitoring
  include_role:
    name: elastic.beats
  vars:
    beats_version: 7.11.1
    beat: filebeat
    beat_conf:
      setup:
        template:
          name: logs-drive-abci-%{[agent.version]}
          type: index
          pattern: logs-drive-abci-%{[agent.version]}-*
      filebeat:
        inputs:
          - type: log
            enabled: true
            json.message_key: msg
            json.keys_under_root: false
            exclude_files: ['\.gz$']
            index: "logs-drive-abci-%{[agent.version]}"
            paths:
              - "{{ mn_evo_services_path }}/logs/drive-json*.log*"
            processors:
              - timestamp:
                  field: json.time
                  layouts:
                    - UNIX_MS
              - if:
                  equals:
                    json.level: 10
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: trace
              - if:
                  equals:
                    json.level: 20
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: debug
              - if:
                  equals:
                    json.level: 30
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: info
              - if:
                  equals:
                    json.level: 40
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: warn
              - if:
                  equals:
                    json.level: 50
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: error
              - if:
                  equals:
                    json.level: 60
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: fatal
              - add_fields:
                  target: event
                  fields:
                    dataset: "drive-abci.log"
              - rename:
                  fields:
                    - from: "json.msg"
                      to: "message"
                  ignore_missing: true
                  fail_on_error: true
              - drop_fields:
                  fields:
                    - json.pid
                    - json.hostname
                    - json.time
                  ignore_missing: true
          - type: log
            enabled: true
            json.message_key: _msg
            json.keys_under_root: false
            exclude_files: ['\.gz$']
            index: "logs-drive-tenderdash-%{[agent.version]}"
            paths:
              - "{{ mn_evo_services_path }}/logs/tenderdash-json*.log*"
            processors:
              - add_fields:
                  target: event
                  fields:
                    dataset: "drive-tenderdash.log"
              - rename:
                  fields:
                    - from: "json._msg"
                      to: "message"
                  ignore_missing: true
                  fail_on_error: true
              - rename:
                  fields:
                    - from: "json.level"
                    - to: "log.level"
    output_conf:
      elasticsearch:
        hosts:
          - "{{ hostvars['logs'].private_ip }}:9200"
        username: "{{ elastic_username }}"
        password: "{{ elastic_password }}"
    logging_conf:
      level: info
      files:
        rotateeverybytes: 10485760
