---

- name: get core container id
  command: docker ps -aqf "name=dashd"
  register: core_container_id

- name: get tenderdash container id
  command: docker ps -aqf "name=mn_evo_services_tendermint"
  register: tenderdash_container_id

- include_vars:
    file: common.yml

- include_vars:
    file: core.yml

- include_vars:
    file: platform.yml
  when: tenderdash_container_id.stdout != ""

- set_fact:
    filebeat_inputs: "{{ [filebeat_inputs, filebeat_platform_inputs] | community.general.lists_mergeby('index') }}"
  when: tenderdash_container_id.stdout != ""

- name: set up filebeat log monitoring
  include_role:
    name: geerlingguy.filebeat
