---

- name: get core container id
  command: docker ps -aqf "name=dashd"
  register: core_container_id

- name: get tenderdash container id
  command: docker ps -aqf "name=mn_evo_services_tendermint"
  register: tenderdash_container_id

- name: set up filebeat log monitoring
  include_role:
    name: geerlingguy.filebeat
  vars:
    filebeat_version: 8.x
    filebeat_package: "filebeat={{ elastic_version }}"
    filebeat_inputs:
      - type: container
        enabled: true
        index: "logs-core-{{ dash_network_name }}-%{[agent.version]}"
        paths:
          - '/var/lib/docker/containers/{{ core_container_id.stdout }}*/*.log'
        processors:
          - add_fields:
              target: event
              fields:
                dataset: "core-{{ dash_network_name }}"
          - dissect:
              tokenizer: "%{?timestamp} %{message}"
              overwrite_keys: true
              target_prefix: ""
      - type: log
        enabled: true
        json.message_key: msg
        json.keys_under_root: false
        exclude_files: ['\.gz$']
        index: "logs-drive.abci-{{ dash_network_name }}-%{[agent.version]}"
        paths:
          - "{{ mn_evo_services_path }}/logs/drive-json*.log*"
        processors:
          - timestamp:
              field: json.time
              layouts:
                - UNIX_MS
          - if:
              equals:
                json.level: 10
            then:
              - add_fields:
                  target: log
                  fields:
                    level: trace
          - if:
              equals:
                json.level: 20
            then:
              - add_fields:
                  target: log
                  fields:
                    level: debug
          - if:
              equals:
                json.level: 30
            then:
              - add_fields:
                  target: log
                  fields:
                    level: info
          - if:
              equals:
                json.level: 40
            then:
              - add_fields:
                  target: log
                  fields:
                    level: warn
          - if:
              equals:
                json.level: 50
            then:
              - add_fields:
                  target: log
                  fields:
                    level: error
          - if:
              equals:
                json.level: 60
            then:
              - add_fields:
                  target: log
                  fields:
                    level: fatal
          - add_fields:
              target: event
              fields:
                dataset: "drive.abci-{{ dash_network_name }}"
          - rename:
              fields:
                - from: "json.msg"
                  to: "message"
              ignore_missing: true
              fail_on_error: true
          - drop_fields:
              fields:
                - json.pid
                - json.hostname
                - json.time
              ignore_missing: true
      - type: container
        enabled: true
        json.message_key: _msg
        json.keys_under_root: false
        index: "logs-drive.tenderdash-{{ dash_network_name }}-%{[agent.version]}"
        paths:
          - '/var/lib/docker/containers/{{ tenderdash_container_id.stdout }}*/*.log'
        processors:
          - add_fields:
              target: event
              fields:
                dataset: "drive.tenderdash-{{ dash_network_name }}"
          - rename:
              fields:
                - from: "json._msg"
                  to: "message"
              ignore_missing: true
              fail_on_error: true
          - rename:
              fields:
                - from: "json.level"
                - to: "log.level"
    filebeat_output_elasticsearch_enabled: true
    filebeat_output_elasticsearch_hosts:
      - "{{ hostvars['logs-1'].private_ip }}:9200"
    filebeat_output_elasticsearch_auth:
      username: "{{ elastic_username }}"
      username: "{{ elastic_password }}"
    filebeat_enable_logging: true
    filebeat_log_level: info
