---

# Requires "payment_targets" and "amount" variables

- name: Populate payment addresses and values
  set_fact:
    payments: "{{ payments | default( {} ) | combine( { item: amount } ) }}"
  with_items:
    - '{{ payment_targets }}'

- name: Show list of payments to be made
  debug:
    var: payments

- name: Fund {{ amount }} coin(s) to listed masternodes
  command: "dash-cli {{ faucet_rpc_args }} sendmany '' '{{ payments|to_json }}'"
  register: fund_result

- name: wait for funding TX {{ fund_result.stdout }} to appear on MN ctrl node
  shell: dash-cli {{ masternode_wallet_rpc_args }} getrawtransaction {{ fund_result.stdout }}
  register: check_result
  until: check_result.rc == 0
  retries: 10
  delay: 5
