---

- name: Create tenderdash dir
  ansible.builtin.file:
    path: '{{ tenderdash_compose_path }}'
    state: directory
    recurse: true

- name: Copy files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ tenderdash_compose_path }}/{{ item }}'
    mode: "0644"
  loop:
    - docker-compose.yml

- name: Create tenderdash config dir
  ansible.builtin.file:
    path: '{{ tenderdash_compose_path }}/tenderdash/config'
    state: directory
    owner: '{{ tenderdash_uid }}'
    group: '{{ tenderdash_gid }}'
    mode: "0750"

- name: Create tenderdash data dir
  ansible.builtin.file:
    path: '{{ tenderdash_compose_path }}/tenderdash/data'
    state: directory
    owner: '{{ tenderdash_uid }}'
    group: '{{ tenderdash_gid }}'
    mode: "0750"

- name: Create tenderdash configs
  vars:
    template_bootstrap_peers: "{{ groups.seed_nodes | reject('equalto', inventory_hostname) }}"
  ansible.builtin.template:
    src: 'roles/tenderdash/templates/tenderdash/{{ item }}.j2'
    dest: '{{ tenderdash_compose_path }}/tenderdash/config/{{ item }}'
    owner: '{{ tenderdash_uid }}'
    group: '{{ tenderdash_gid }}'
    mode: "0644"
  loop:
    - config.toml
    - genesis.json
    - node_key.json

- name: Start tenderdash
  community.docker.docker_compose_v2:
    project_src: '{{ tenderdash_compose_path }}'
    state: present
    pull: always
    recreate: always

- name: Configure logrotate for Tenderdash logs
  ansible.builtin.copy:
    dest: /etc/logrotate.d/tenderdash
    content: |
      {{ tenderdash_compose_path }}/tenderdash/logs/*.log {
          daily
          rotate 1
          compress
          delaycompress
          missingok
          notifempty
          create 0640 {{ tenderdash_uid }} {{ tenderdash_gid }}
      }
    owner: '{{ tenderdash_uid }}'
    group: '{{ tenderdash_gid }}'
    mode: '0640'

- name: Add Logstash filter for Tenderdash TRACE logs
  ansible.builtin.lineinfile:
    path: /etc/logstash/conf.d/tenderdash.conf
    line: |
      filter {
        if [log_level] == "trace" {
          drop { }
        }
      }
