---

- name: Create .dashcore directory for each user
  ansible.builtin.file:
    path: '{{ item.dir }}/.dashcore'
    state: directory
    mode: "0755"
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
  loop: '{{ users }}'

- name: Symlink dash.conf to user dashmate directory to make rpc work
  ansible.builtin.file:
    path: '{{ item.dir }}/.dashcore/dash.conf'
    src: '/etc/dash.conf'
    state: link
    force: true
  loop: '{{ users }}'
