---

- name: Merge user lists
  ansible.builtin.set_fact:
    users_to_manage: "{{ users_to_manage + users }}"
  when: users is defined

- name: Pull dashd image
  community.docker.docker_image:
    name: '{{ dashd_image }}'
    source: pull

- name: Copy dash-cli from docker container
  community.docker.docker_container:
    name: copysource
    auto_remove: true
    volumes:
      - /tmp:/host-tmp
    image: '{{ dashd_image }}'
    command: cp /usr/local/bin/dash-cli /host-tmp/

- name: Install dash-cli in path
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/dash-cli
    dest: /usr/local/bin/dash-cli
    mode: "0755"

- name: Create .dashcore directory for each user
  ansible.builtin.file:
    path: '{{ item.dir }}/.dashcore'
    state: directory
    mode: 0755
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
  loop: '{{ users_to_manage }}'

- name: Write dash.conf file in /etc/
  ansible.builtin.template:
    src: dash.conf.j2
    dest: /etc/dash.conf
    owner: root
    group: root
    mode: "0644"
- debug:
    var: users

- name: Symlink dash.conf to user dashmate directory to make rpc work
  ansible.builtin.file:
    path: '{{ item.dir }}/.dashcore/dash.conf'
    src: '/etc/dash.conf'
    state: link
    force: true
  loop: '{{ users_to_manage }}'
