---

- name: Set swap_file variable
  set_fact:
    swap_file: /swapfile

- name: Check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  command: fallocate -l {{ swap_space }} {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Format swap file
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: Turn on swap
  command: swapon -av
  register: result
  changed_when: '"already active" not in result.stdout'

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "10"
  register: swappiness

- name: Reset swap usage
  shell: swapoff -a && swapon -a
  when: swappiness.changed
