---

# Requires "masternode_names" variable

- name: import masternode owner private key
  command: 'dash-cli {{ masternode_wallet_rpc_args }} importprivkey {{ masternodes[item].owner.private_key }} "" false'
  with_items: '{{ masternode_names }}'

- name: rescan blockchain
  command: 'dash-cli {{ masternode_wallet_rpc_args }} rescanblockchain'

# fund

- name: Populate payment targets
  set_fact:
    target_addresses: "{{ target_addresses | default([]) + [ masternodes[item].collateral.address ] }}"
  with_items:
    - "{{ masternode_names }}"

- name: check if address contains a suitable fee utxo
  command: "dash-cli {{ masternode_wallet_rpc_args }} listunspent 1 99999999 '{{ target_addresses|to_json }}' false '{{ maxamount|to_json }}' "
  register: funded_addresses
  vars:
    maxamount:
      maximumAmount: 1

- name: Figure out which addresses still need funding
  set_fact:
    fee_missing_addresses: "{{ target_addresses | difference(funded_addresses.stdout) }}"

- name: fund 1 coin for ProTx
  include_tasks: ./roles/mn-fund-collateral/tasks/fund_collateral.yml
  vars:
    amount: 1
    payment_targets: '{{ fee_missing_addresses }}'
  when: fee_missing_addresses|length > 0

- name: generate at least one block to confirm funding transactions
  include_role:
    name: generate-blocks
  vars:
    num_blocks: 1
    balance_needed: 0

# register

- include_tasks: createprovidertx.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
  with_items: '{{ masternode_names }}'

- name: generate at least one block to confirm protxs
  include_role:
    name: generate-blocks
  vars:
    num_blocks: 1
    balance_needed: 0

# verify

- name: get list of ProTx transactions from the wallet
  command: dash-cli protx list wallet true
  register: get_protx_list_result

- set_fact:
    registered_masternode_names: []

- name: get names of registered masternodes
  set_fact:
    registered_masternode_names: "{{ registered_masternode_names|default([]) + [ item ] }}"
  when: get_protx_list_result.stdout|from_json|json_query("[?state.ownerAddress=='" + masternodes[item].owner.address + "']")
  with_items: '{{ masternode_names }}'

- fail:
    msg: ProTX transactions were not created
  when: masternode_names | difference(registered_masternode_names)
