version: '2'

services:
  sentinel:
    image: ablock/sentinel
    restart: always
    environment:
      - DEBUG=false
      - RPCUSER={{ dashd_rpcuser }}
      - RPCPASSWORD={{ dashd_rpcpassword }}
      - RPCHOST={{ private_ip }}
      - RPCPORT={{ dashd_rpcport }}
      # Sentinel only supports mainnet and testnet at the moment
      - NETWORK={{ 'mainnet' if dash_network == 'mainnet' else 'testnet' }}
      # Bypass scheduler
      - SENTINEL_ARGS=-b
