---

# Option: generate blocks

- name: Get start block count
  command: dash-cli {{ faucet_rpc_args }} getblockcount
  register: start_block_count
  when: num_blocks|int > 0

- name: generate {{ num_blocks }} block(s)
  shell: dash-cli {{ faucet_rpc_args }} generatetoaddress {{ num_blocks }} {{ miner_payment_address }} > /dev/null && dash-cli {{ faucet_rpc_args }} getblockcount
  when: num_blocks|int > 0
  register: current_block_count
  until: current_block_count.stdout|int >= start_block_count.stdout|int + num_blocks|int
  retries: 200
  delay: 0

- name: Wait for generated block to appear on MN ctrl node
  command: "dash-cli {{ masternode_wallet_rpc_args }} getblockcount"
  register: check_result
  until: check_result.stdout|int == current_block_count.stdout|int
  retries: 10
  delay: 2

# Option: generate balance

# TODO avoid first call if not needed
- name: generate enough blocks to have {{ balance_needed|default(0) }} coins
  shell: dash-cli {{ faucet_rpc_args }} generatetoaddress 10 {{ miner_payment_address }} > /dev/null && dash-cli {{ faucet_rpc_args }} getbalance
  when: balance_needed|float > 0
  register: balance_result
  until: balance_result.stdout|float >= balance_needed|float
  retries: 200
  delay: 0

- set_fact:
    new_balance: "{{ balance_result.stdout|float }}"
  when: balance_needed|float > 0
