---

# Requires "masternode" and "masternode_name" variables

- name: Create ProTx for {{ masternode_name ~ '/' ~ masternode.owner.address }}
  ansible.builtin.command: "dash-cli -rpcwallet={{ wallet_rpc_wallet_mno }} protx register
            {{ vars['collateral_txid_' + masternode_name | replace('-', '_')] }}
            {{ vars['collateral_vout_' + masternode_name | replace('-', '_')] }}
            {{ hostvars[masternode_name].public_ip }}:{{ dashd_port }}
            {{ masternode.owner.address }}
            {{ masternode.operator.public_key }}
            {{ masternode.owner.address }}
            0
            {{ miner_payment_address }}
            {{ masternode.collateral.address }}"
  register: protx
  changed_when: protx.stdout | length == 64
  when: mn_group_name == "masternodes"

- name: Create HP ProTx for {{ masternode_name ~ '/' ~ masternode.owner.address }}
  ansible.builtin.command: "dash-cli -rpcwallet={{ wallet_rpc_wallet_mno }} protx register_hpmn
            {{ vars['collateral_txid_' + masternode_name | replace('-', '_')] }}
            {{ vars['collateral_vout_' + masternode_name | replace('-', '_')] }}
            {{ hostvars[masternode_name].public_ip }}:{{ dashd_port }}
            {{ masternode.owner.address }}
            {{ masternode.operator.public_key }}
            {{ masternode.owner.address }}
            0
            {{ miner_payment_address }}
            {{ masternode.node_key.id }}
            {{ tendermint_p2p_port }}
            {{ dapi_port }}
            {{ masternode.collateral.address }}"
  register: protx
  changed_when: protx.stdout | length == 64
  when: mn_group_name == "hp_masternodes"
