---

# register

- name: Create provider registration transaction
  ansible.builtin.include_tasks: createprovidertx.yml
  vars:
    masternode: '{{ hostvars[item][mn_group_name][item] }}'
    masternode_name: '{{ item }}'
  with_items: '{{ masternode_names }}'

# sometimes not all protx get mined in the first block
- name: Generate at least two blocks to confirm protxs
  ansible.builtin.include_role:
    name: generate_blocks
  vars:
    num_blocks: 2
    balance_needed: 0

# verify


- name: Initialize array for registered masternodes
  ansible.builtin.set_fact:
    registered_masternode_names: []

- name: Get list of ProTx transactions from the wallet
  ansible.builtin.command: dash-cli -rpcwallet={{ wallet_rpc_wallet_mno }} protx list wallet true
  register: get_protx_list_result
  changed_when: get_protx_list_result.stdout | to_json | length > 0

- name: Get names of registered masternodes
  ansible.builtin.set_fact:
    registered_masternode_names: '{{ registered_masternode_names + [item] }}'
  when: get_protx_list_result.stdout | from_json | json_query("[?state.ownerAddress=='" + [hostvars[item][mn_group_name][item]['owner']['address'] + "']")
  with_items: '{{ masternode_names }}'

- name: Fail if masternodes were not registered
  ansible.builtin.fail:
    msg: ProTX transactions were not created
  when: masternode_names | difference(registered_masternode_names)
