---

# Requires "masternode_names" variable

- name: Import masternode owner private key
  ansible.builtin.command: 'dash-cli {{ masternode_wallet_rpc_args }} importprivkey {{ masternodes[item].owner.private_key }} "" false'
  with_items: '{{ masternode_names }}'
  register: result
  changed_when: result.rc == 0

- name: Rescan blockchain
  ansible.builtin.command: 'dash-cli {{ masternode_wallet_rpc_args }} rescanblockchain'
  register: result
  changed_when: result.stdout | to_json | query('stop_height') > 1

# fund

- name: Fund 1 coin for ProTx
  ansible.builtin.include_tasks: ./roles/mn_fund_collateral/tasks/fund_collateral.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
    amount: 1
  with_items: '{{ masternode_names }}'

- name: Generate at least one block to confirm funding transactions
  ansible.builtin.include_role:
    name: generate_blocks
  vars:
    num_blocks: 1
    balance_needed: 0

- name: Create provider registration transaction
  ansible.builtin.include_tasks: createprovidertx.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
  with_items: '{{ masternode_names }}'


- name: Generate at least one block to confirm protxs
  ansible.builtin.include_role:
    name: generate_blocks
  vars:
    num_blocks: 1
    balance_needed: 0

# verify

- name: Get list of ProTx transactions from the wallet
  ansible.builtin.command: dash-cli protx list wallet true
  register: get_protx_list_result
  changed_when: get_protx_list_result.stdout | to_json | length > 0

- name: Get names of registered masternodes
  ansible.builtin.set_fact:
    registered_masternode_names: "{{ registered_masternode_names | default([]) + [item] }}"
  when: get_protx_list_result.stdout | from_json | json_query("[?state.ownerAddress=='" + masternodes[item].owner.address + "']")
  with_items: '{{ masternode_names }}'

- name: Fail if masternodes were not registered
  ansible.builtin.fail:
    msg: ProTX transactions were not created
  when: masternode_names | difference(registered_masternode_names)
