---

- name: Create a directories for the project
  ansible.builtin.file:
    path: '{{ metrics_path }}'
    state: directory
    recurse: yes
    owner: '{{ metrics_user }}'
    group: '{{ metrics_user }}'
    mode: "0755"
  loop:
    - /home/{{ ansible_user }}/metrics/prometheus/config
    - /home/{{ ansible_user }}/metrics/grafana
    - /home/{{ ansible_user }}/metrics/haproxy

- name: Copy haproxy and prometheus rules
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ item }}"
      owner: '{{ metrics_user }}'
      group: '{{ metrics_user }}'
      mode: "0644"
  loop:
      - haproxy/haproxy.cfg
      - prometheus/rules.yml

- name: Copy prometheus config
  ansible.builtin.template:
      src: prometheus.yml.j2
      dest: prometheus.yml
      owner: '{{ metrics_user }}'
      group: '{{ metrics_user }}'
      mode: "0644"

- name: Start metrics
  community.docker.docker_compose:
    project_src: /path/to/docker-compose-file-directory
    restart: yes
    state: present
