---

- name: Create a directories for the project
  ansible.builtin.file:
    path: '{{ metrics_path }}'
    state: directory
    recurse: yes
    owner: '{{ metrics_user }}'
    group: '{{ metrics_user }}'
    mode: '0755'
  loop:
    - '{{ metrics_path }}/prometheus/config'
    - '{{ metrics_path }}/grafana'
    - '{{ metrics_path }}/haproxy'

- name: Copy haproxy configs and prometheus rules
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ metrics_path }}/{{ item }}'
    owner: '{{ metrics_user }}'
    group: '{{ metrics_user }}'
    mode: '0644'
  loop:
    - haproxy/haproxy.cfg
    - prometheus/rules.yml

- name: Render prometheus and docker compose configs
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ metrics_path }}/{{ item }}'
    owner: '{{ metrics_user }}'
    group: '{{ metrics_user }}'
    mode: '0644'
  loop:
    - prometheus.yml
    - docker-compose.yml

- name: Start metrics
  community.docker.docker_compose:
    project_src: '{{ metrics_path }}'
    restart: yes
    state: present
