---
- name: Install Metricbeat
  ansible.builtin.apt:
    name: metricbeat
    state: present
    update_cache: true
  become: true

- name: Copy Metricbeat module configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/metricbeat/modules.d/{{ item | basename }}"
    mode: '0644'
  loop: "{{ query('ansible.builtin.fileglob', 'modules.d/*.yml', wantlist=True) }}"
  notify: Restart Metricbeat
  become: true

- name: Configure Metricbeat
  ansible.builtin.template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    mode: '0644'
  notify: Restart Metricbeat
  become: true

- name: Enable and start Metricbeat service
  ansible.builtin.systemd:
    name: metricbeat
    enabled: true
    state: started
  become: true
