---

- name: Get list of ProTx transactions from the wallet
  ansible.builtin.command: dash-cli -rpcwallet={{ mno_wallet }} protx list wallet true
  register: get_protx_list_result
  changed_when: get_protx_list_result.stdout | from_json | length > 0

- name: Get names of registered masternodes
  ansible.builtin.set_fact:
    registered_masternode_names: "{{ registered_masternode_names | default([]) + [item] }}"
  when: get_protx_list_result.stdout | from_json | json_query("[?state.ownerAddress=='" + masternodes[item].owner.address + "']")
  with_items: '{{ groups["masternodes"] }}'

- name: Set empty outer scope variable for protx list
  ansible.builtin.set_fact:
    registered_masternode_protx: []

- name: Get list of registered masternode protx
  ansible.builtin.include_tasks: find_protx.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
  with_items: '{{ registered_masternode_names }}'

- name: Write protx values to inventory file
  become: false
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: ../networks/{{ dash_network_name }}.inventory # relative to playbook
    regexp: '^({{ item.masternode }} (?!.*protx=).*)'
    line: '\1 protx={{ item.protx }}'
    backrefs: true
  with_items: '{{ registered_masternode_protx }}'
