---

filebeat_platform_inputs:
  - type: container
    enabled: true
    index: "logs-core-{{ dash_network_name }}-%{[agent.version]}"
    paths:
      - '/var/lib/docker/containers/{{ dashmate_core_host_info.containers[0].Id }}/*.log'
    processors:
      - add_fields:
          target: event
          fields:
            dataset: "core-{{ dash_network_name }}"
      - dissect:
          tokenizer: "%{?timestamp} %{message}"
          overwrite_keys: true
          target_prefix: ""
  - type: log
    enabled: "{{ dashmate_tenderdash_host_info.containers | length > 0 }}"
    json.message_key: msg
    json.keys_under_root: false
    exclude_files: ['\.gz$']
    index: "logs-drive.abci-{{ dash_network_name }}-%{[agent.version]}"
    paths:
      - "{{ dashmate_logs_dir }}/drive-json*.log*"
    processors:
      - timestamp:
          field: json.time
          layouts:
            - UNIX_MS
      - if:
          equals:
            json.level: 10
        then:
          - add_fields:
              target: log
              fields:
                level: trace
      - if:
          equals:
            json.level: 20
        then:
          - add_fields:
              target: log
              fields:
                level: debug
      - if:
          equals:
            json.level: 30
        then:
          - add_fields:
              target: log
              fields:
                level: info
      - if:
          equals:
            json.level: 40
        then:
          - add_fields:
              target: log
              fields:
                level: warn
      - if:
          equals:
            json.level: 50
        then:
          - add_fields:
              target: log
              fields:
                level: error
      - if:
          equals:
            json.level: 60
        then:
          - add_fields:
              target: log
              fields:
                level: fatal
      - add_fields:
          target: event
          fields:
            dataset: "drive.abci-{{ dash_network_name }}"
      - rename:
          fields:
            - from: "json.msg"
              to: "message"
          ignore_missing: true
          fail_on_error: true
      - drop_fields:
          fields:
            - json.pid
            - json.hostname
            - json.time
          ignore_missing: true
  - type: container
    enabled: "{{ dashmate_tenderdash_host_info.containers | length > 0 }}"
    json.message_key: message
    json.keys_under_root: false
    index: "logs-drive.tenderdash-{{ dash_network_name }}-%{[agent.version]}"
    paths:
      - '/var/lib/docker/containers/{{ dashmate_tenderdash_host_info.containers[0].Id }}/*.log'
    processors:
      - add_fields:
          target: event
          fields:
            dataset: "drive.tenderdash-{{ dash_network_name }}"
      - rename:
          fields:
            - from: "json._msg"
              to: "message"
          ignore_missing: true
          fail_on_error: true
      - rename:
          fields:
            - from: "json.level"
            - to: "log.level"
