---

- name: create masternode evolution services dir
  file:
    path: '{{ mn_evo_services_path }}'
    state: directory
    recurse: true

- name: copy files
  template:
    src: '{{ item }}.j2'
    dest: '{{ mn_evo_services_path }}/{{ item }}'
  loop:
    - docker-compose.yml
    - dapi-nginx.conf
    - dapi-nginx-grpc.conf
    - dapi-nginx-errors.grpc_conf
    - .env
    - dapi-envoy.yaml

- import_tasks: mongodb_replicaset.yml

- import_tasks: tendermint.yml

- name: start masternodes evolution services
  docker_compose:
    project_src: '{{ mn_evo_services_path }}'
    state: present
    restarted: yes
    pull: yes
