---

- name: create masternode evolution services dir
  file: path='{{ mn_evo_services_path }}' state=directory recurse=true

- name: copy files
  template:
    src: '{{ item }}.j2'
    dest: '{{ mn_evo_services_path }}/{{ item }}'
  loop:
    - docker-compose.yml
    - .env

- import_tasks: ipfs/main.yml

- name: start masternodes evolution services
  docker_service:
    project_src: '{{ mn_evo_services_path }}'
    state: present
    restarted: yes
    pull: yes

- name: check DashDrive sync container
  assert:
    that: 'drive_sync.drive_sync.state.running'

- name: check DashDrive API container
  assert:
    that: 'drive_api.drive_api.state.running'

- name: check DashDrive MongoDB container
  assert:
    that: 'drive_mongodb.drive_mongodb.state.running'

- name: check DAPI container
  assert:
    that: 'dapi.dapi.state.running'
