---

- name: create masternode evolution services dir
  file:
    path: '{{ mn_evo_services_path }}'
    state: directory
    recurse: true

- name: copy files
  template:
    src: '{{ item }}.j2'
    dest: '{{ mn_evo_services_path }}/{{ item }}'
  loop:
    - docker-compose.yml
    - dapi-nginx.conf
    - dapi-nginx-grpc.conf
    - dapi-nginx-errors.grpc_conf
    - .env

- import_tasks: mongodb_replicaset.yml

- import_tasks: tendermint.yml

- name: start masternodes evolution services
  docker_compose:
    project_src: '{{ mn_evo_services_path }}'
    state: present
    restarted: yes
    pull: yes

- name: check Drive MongoDB container
  assert:
    that: 'drive_mongodb.drive_mongodb.state.running'

- name: check Drive Update State container
  assert:
    that: 'drive_update_state.drive_update_state.state.running'

- name: check Drive API container
  assert:
    that: 'drive_api.drive_api.state.running'

- name: check Machine container
  assert:
    that: 'machine.machine.state.running'

- name: check Tendermint container
  assert:
    that: 'tendermint.tendermint.state.running'

- name: check DAPI Core container
  assert:
    that: 'dapi_core.dapi_core.state.running'

- name: check DAPI TxFilterStream container
  assert:
    that: 'dapi_tx_filter_stream.dapi_tx_filter_stream.state.running'

- name: check DAPI Nginx container
  assert:
    that: 'dapi_nginx.dapi_nginx.state.running'
