---

- name: start MongoDB
  docker_compose:
    project_src: '{{ mn_evo_services_path }}'
    services:
      - drive_mongodb
    state: present
    pull: yes

- name: initialize MongoDB replica set
  mongodb_replicaset:
    login_host: "localhost"
    login_port: "27017"
    replica_set: "driveDocumentIndices"
    members:
      - "drive_mongodb:27017"
    validate: no

- name: check MongoDB replica set status
  command: "docker-compose exec -T drive_mongodb mongo mongodb://drive_mongodb:27017/?replicaSet=driveDocumentIndices --quiet --eval='rs.status()'"
  args:
    chdir: '{{ mn_evo_services_path }}'
  register: connect_to_replica
  retries: 12
  delay: 5
  until: "connect_to_replica.rc == 0 and connect_to_replica.stdout.find('\"ok\" : 1')"
