---

- name: create tendermint home dir
  file:
    path: '{{ mn_evo_services_path }}/tendermint'
    state: directory
    owner: '{{ tendermint_uid }}'
    group: '{{ tendermint_gid }}'
    mode: 0750

- name: create tendermint config dir
  file:
    path: '{{ mn_evo_services_path }}/tendermint/config'
    state: directory
    owner: '{{ tendermint_uid }}'
    group: '{{ tendermint_gid }}'
    mode: 0750

- name: create tendermint data dir
  file:
    path: '{{ mn_evo_services_path }}/tendermint/data'
    state: directory
    owner: '{{ tendermint_uid }}'
    group: '{{ tendermint_gid }}'
    mode: 0750

- name: create Tendermint configs
  template:
    src: 'roles/mn-evo-services/templates/tendermint/{{ item }}.j2'
    dest: '{{ mn_evo_services_path }}/tendermint/config/{{ item }}'
    owner: '{{ tendermint_uid }}'
    group: '{{ tendermint_gid }}'
  loop:
    - config.toml
    - genesis.json
    - node_key.json
