---

- name: Ensure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create daemon.json
  template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0640
  register: daemon_json_state

- name: Update systemd service
  become: true
  copy:
    src: '{{ item }}'
    dest: '/lib/systemd/system/{{ item }}'
    mode: 0644
  loop:
    - 'docker.service'
    - 'docker.socket'
  register: daemon_systemd_state

- name: Update upstart defaults
  become: true
  copy:
    src: docker
    dest: /etc/default/
    mode: 0644

- name: Restart docker
  service:
    name: docker
    state: restarted
    daemon_reload: true
  when: daemon_json_state is changed or daemon_systemd_state is changed
