version: '3'

services:
  sentinel:
    image: ablock/sentinel
    restart: always
    environment:
      - DEBUG=false
      - RPCUSER={{ dashd_rpcuser }}
      - RPCPASSWORD={{ dashd_rpcpassword }}
      - RPCHOST={{ private_ip }}
      - RPCPORT={{ dashd_rpcport }}
      # Sentinel only supports mainnet and testnet at the moment
      - NETWORK={{ 'mainnet' if dash_network == 'mainnet' else 'testnet' }}
      # Bypass scheduler
      - SENTINEL_ARGS=-b

  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    command: daemon --enable-gc --migrate --enable-pubsub-experiment
    environment:
      LIBP2P_FORCE_PNET: 1
      SWARM_KEY: ${SWARM_KEY}
      SWARM_PEER: ${SWARM_PEER}
    ports:
      - 4001:4001
      - 5001:5001
    volumes:
      - ipfs:/data/ipfs
      - {{ mn_services_path }}/ipfs/init.sh:/usr/local/bin/start_ipfs

  mongodb:
    image: mongo:3.6

  drive_sync:
    image: 103738324493.dkr.ecr.us-west-2.amazonaws.com/dashevo/dashdrive:latest
    restart: always
    command: npm run sync
    environment:
      - DASHCORE_JSON_RPC_USER={{ dashd_rpcuser }}
      - DASHCORE_JSON_RPC_PASS={{ dashd_rpcpassword }}
      - DASHCORE_JSON_RPC_HOST={{ private_ip }}
      - DASHCORE_JSON_RPC_PORT={{ dashd_rpcport }}
      - STORAGE_MONGODB_DB=drive_main
      - STORAGE_MONGODB_URL=mongodb://mongodb:27017
      - STORAGE_IPFS_MULTIADDR=/ip4/{{ private_ip }}/tcp/5001
    depends_on:
      - ipfs
      - mongodb

  drive_api:
    image: 103738324493.dkr.ecr.us-west-2.amazonaws.com/dashevo/dashdrive:latest
    restart: always
    command: npm run api
    environment:
      - DASHCORE_JSON_RPC_USER={{ dashd_rpcuser }}
      - DASHCORE_JSON_RPC_PASS={{ dashd_rpcpassword }}
      - DASHCORE_JSON_RPC_HOST={{ private_ip }}
      - DASHCORE_JSON_RPC_PORT={{ dashd_rpcport }}
      - STORAGE_MONGODB_DB=drive_main
      - STORAGE_MONGODB_URL=mongodb://mongodb:27017
      - STORAGE_IPFS_MULTIADDR=/ip4/{{ private_ip }}/tcp/5001
    depends_on:
      - ipfs
      - mongodb
    ports:
      - 6000:6000

volumes:
  ipfs:
