version: '3'

services:
  sentinel:
    image: ablock/sentinel
    restart: always
    environment:
      - DEBUG=false
      - RPCUSER={{ dashd_rpcuser }}
      - RPCPASSWORD={{ dashd_rpcpassword }}
      - RPCHOST={{ private_ip }}
      - RPCPORT={{ dashd_rpcport }}
      # Sentinel only supports mainnet and testnet at the moment
      - NETWORK={{ 'mainnet' if dash_network == 'mainnet' else 'testnet' }}
      # Bypass scheduler
      - SENTINEL_ARGS=-b

  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    command: daemon --enable-gc --migrate --enable-pubsub-experiment
    environment:
      LIBP2P_FORCE_PNET: 1
      SWARM_KEY: ${SWARM_KEY}
      SWARM_PEER: ${SWARM_PEER}
    ports:
      - 4001:4001
    volumes:
      - ipfs:/data/ipfs
      - {{ mn_services_path }}/ipfs/init.sh:/usr/local/bin/start_ipfs

volumes:
  ipfs:
