---

# Option: generate blocks

- name: Get start block count
  ansible.builtin.command: dash-cli getblockcount
  register: start_block_count
  when: num_blocks|int > 0

- name: Generate {{ num_blocks }}
  ansible.builtin.shell: >
    dash-cli generatetoaddress {{ num_blocks }} {{ miner_payment_address }} > /dev/null &&
    dash-cli getblockcount
  when: num_blocks|int > 0
  register: current_block_count
  until: current_block_count.stdout|int >= start_block_count.stdout|int + num_blocks|int
  retries: 200
  delay: 0

# Option: generate balance
# TODO avoid first call if not needed
- name: Generate enough blocks to have {{ balance_needed | default(0) }}
  ansible.builtin.shell: >
    dash-cli generatetoaddress 10 {{ miner_payment_address }} > /dev/null &&
    dash-cli getbalance
  when: balance_needed | float > 0
  register: balance_result
  until: balance_result.stdout | float >= balance_needed | float
  retries: 200
  delay: 0

- name: Set resulting balance
  ansible.builtin.set_fact:
    new_balance: "{{ balance_result.stdout | float }}"
  when: balance_needed | float > 0
