---

# Requires "payment_targets" and "amount" variables

- name: Populate payment addresses and values
  ansible.builtin.set_fact:
    payments: "{{ payments | default( {} ) | combine( { item: amount } ) }}"
  with_items:
    - '{{ payment_targets }}'

- name: Show list of payments to be made
  ansible.builtin.debug:
    var: payments

- name: Fund {{ amount }} coin(s) to listed masternodes
  ansible.builtin.command: "dash-cli {{ faucet_rpc_args }} sendmany '' '{{ payments|to_json }}'"
  register: fund_result

- name: Wait for MN ctrl node to confirm receipt of ProTx {{ fund_result.stdout }}
  ansible.builtin.command: 'dash-cli {{ masternode_wallet_rpc_args }} getrawtransaction {{ fund_result.stdout }}'
  register: check_result
  until: check_result.rc == 0
  retries: 10
  delay: 5
  changed_when: check_result.stdout | length > 0
