---

- name: Install jq
  ansible.builtin.package:
    name: jq
    state: present

- name: Copy report generation script
  ansible.builtin.copy:
    src: templates/mn-status-report.sh
    dest: /usr/local/bin
    owner: ubuntu
    group: ubuntu
    mode: 0755
