---

- name: Apparmor disable for tcpdump
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.tcpdump
  ignore_errors: true

- name: Configure tcpdump
  template:
    src: 'tcpdump.service'
    dest: '/etc/systemd/system/tcpdumpd.service'
    mode: 0644

- name: Make sure tcpdump unit is running
  ansible.builtin.systemd:
    state: restarted
    name: tcpdumpd
    daemon_reload: true

- name: Copy logrotate script
  template:
    src: 'tcpdumpd'
    dest: '/etc/logrotate.d/tcpdumpd'
    mode: 0644
