---

- name: Stop dashmate
  ansible.builtin.command: yarn dashmate stop
  become: true
  become_user: dashmate
  args:
    chdir: /home/dashmate/platform
  when: inventory_hostname in groups["masternodes"]
  register: dashmate_stop
  changed_when: "'Node is not running' in dashmate_stop.stderr"

- name: Disable pay-faucet
  ansible.builtin.systemd:
    name: 'pay-faucet'
    state: stopped
    enabled: false
  failed_when: false

- name: Disable dashd-generate-miner
  ansible.builtin.systemd:
    name: 'dashd-generate-miner'
    state: stopped
    enabled: false
  failed_when: false

- name: Collect list of docker services
  community.docker.docker_host_info:
    containers: true
  register: host_info

- name: Stop all docker containers
  community.docker.docker_container:
    name: '{{ item.Id }}'
    state: stopped
  with_items: '{{ host_info.containers }}'

- name: Remove all docker data
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: true
    networks: true
    volumes: true
    builder_cache: true

- name: Unmount data
  ansible.posix.mount:
    path: '{{ elastic_path }}/data'
    state: unmounted
  when: inventory_hostname in groups['logs_nodes']

- name: Delete dashmate config dir
  ansible.builtin.file:
    state: absent
    path: "{{ dashmate_config_dir }}/"
  when: inventory_hostname in groups["masternodes"]

- name: Delete dash home dir
  ansible.builtin.file:
    state: absent
    path: "{{ dashd_home }}/"
