---

- name: Delete dashmate config dir
  ansible.builtin.file:
    state: absent
    path: "{{ dashmate_config_dir }}/"

- name: Delete dashmate logs dir
  ansible.builtin.file:
    state: absent
    path: "{{ dashmate_logs_dir }}/"

- name: Delete dashmate source dir
  ansible.builtin.file:
    state: absent
    path: "{{ dashmate_source_dir }}/"
