---

- name: Set vars
  ansible.builtin.import_tasks: ./set_vars.yml

- name: Create dashmate group
  ansible.builtin.group:
    name: '{{ dashmate_group }}'

- name: Create dashmate user
  ansible.builtin.user:
    name: '{{ dashmate_user }}'
    comment: 'Dashmate user'
    group: '{{ dashmate_group }}'
    home: '{{ dashmate_home }}'
    create_home: true
    shell: /bin/bash
    umask: '0002'

- name: Add dashmate user to docker group
  ansible.builtin.user:
    name: 'dashmate'
    groups: docker
    append: true

- name: Write dash.conf for dash-cli
  ansible.builtin.template:
    src: dash.conf.j2
    dest: /etc/dash.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure users for dash-cli
  ansible.builtin.include_role:
    name: dash_cli
    tasks_from: configure_users
  vars:
    dashmate_user_dict:
      user: '{{ dashmate_user }}'
      group: '{{ dashmate_group }}'
      dir: '{{ dashmate_home }}'
    users: '{{ system_users + [dashmate_user_dict] }}'

- name: Create logs dir
  ansible.builtin.file:
    path: '{{ dashmate_logs_dir }}'
    state: directory
    owner: '{{ dashmate_user }}'
    group: '{{ dashmate_group }}'
    recurse: true

- name: Configure log rotation
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_applications:
      - name: platform-logs
        definitions:
          - logs:
              - '{{ dashmate_logs_dir }}/*.log'
            options:
              - rotate 7
              - daily
              - maxsize 1G
              - missingok
              - notifempty
              - copytruncate
              - compress
              - delaycompress

- name: Ensure logrotate runs hourly under systemd timer
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/logrotate.timer
    regexp: '^OnCalendar=hourly'
    insertafter: '^OnCalendar=daily'
    line: OnCalendar=hourly

- name: Create dashmate config dir
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ dashmate_user }}'
    group: '{{ dashmate_group }}'
    mode: '0755'
  loop:
    - '{{ dashmate_config_dir }}'

- name: Build dashmate
  ansible.builtin.import_tasks: ./build.yml
  when: dashmate_branch is defined

- name: Install dashmate
  ansible.builtin.import_tasks: ./install.yml
  when: dashmate_version is defined

- name: Retrieve dashmate version
  ansible.builtin.command: "{{ dashmate_cmd }} --version"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_version_result
  changed_when: dashmate_version_result.rc == 0

- name: Extract dashmate version
  ansible.builtin.set_fact:
    dashmate_config_version: "{{ (dashmate_version_result.stdout | split(' ') | first() | split('/'))[1] }}"

- name: Write dashmate config file
  vars:
    template_bootstrap_peers: "{{ groups.seed_nodes | reject('equalto', inventory_hostname) }}"
  ansible.builtin.template:
    src: dashmate.json.j2
    dest: '{{ dashmate_config_dir }}/config.json'
    owner: '{{ dashmate_user }}'
    group: '{{ dashmate_group }}'
    mode: "0644"
  register: template_result

- name: Generate self-signed SSL certificate for DAPI
  ansible.builtin.import_tasks: ./ssl/self_signed.yml
  when: dashmate_platform_enable and dashmate_platform_dapi_envoy_ssl_provider == 'self-signed'

- name: Obtain ZeroSSL certificate for DAPI
  ansible.builtin.import_tasks: ./ssl/zerossl.yml
  when: dashmate_platform_enable and dashmate_platform_dapi_envoy_ssl_provider == 'zerossl'

- name: Export current dashmate config
  ansible.builtin.shell: "{{ dashmate_cmd }} config envs > {{ dashmate_home }}/.env"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_envs
  changed_when: dashmate_envs.rc == 0

- name: Update dashmate images
  ansible.builtin.command: "{{ dashmate_cmd }} update --format=json"
  become: true
  become_user: dashmate
  register: dashmate_update
  args:
    chdir: '{{ dashmate_cwd }}'
  changed_when: dashmate_update.rc == 0

- name: Get service statuses
  ansible.builtin.command: "{{ dashmate_cmd }} status services --format=json"
  become: true
  become_user: dashmate
  changed_when: dashmate_services_status.rc == 0
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_services_status

- name: Set facts
  ansible.builtin.set_fact:
    is_core_started: >-
      {{
        dashmate_services_status.stdout |
        from_json |
        json_query('[?service==`core`&&status!=`not_started`]') |
        length | int > 0
      }}
    is_platform_started: >-
      {{
        dashmate_services_status.stdout |
        from_json |
        json_query('[?service!=`core`&&service!=`sentinel`&&status!=`not_started`]') |
        length | int > 0
      }}
    is_core_images_updated: >-
      {{
        dashmate_update.stdout |
        from_json |
        json_query('[?name==`core`||name==`sentinel`]') |
        sort(attribute='updated', reverse=true) |
        first() |
        json_query('updated')
      }}
    is_platform_images_updated: >-
      {{
        dashmate_update.stdout |
        from_json |
        json_query('[?name!=`core`&&name!=`sentinel`]') |
        sort(attribute='updated', reverse=true) |
        first() |
        json_query('updated')
      }}
    is_dashmate_package_changed: "{{ dashmate_install_result.changed }}"
    is_dashmate_config_changed: "{{ template_result.changed }}"

- name: Print status
  ansible.builtin.debug:
    msg: "\n
Core Started: {{ is_core_started }}\n
Platform Started: {{ is_platform_started }}\n
Core Images Updated: {{ is_core_images_updated }}\n
Platform Images Updated: {{ is_platform_images_updated }}\n
Dashmate Package Updated: {{ is_dashmate_package_changed }}\n
Dashmate Config Changed: {{ is_dashmate_config_changed }}\n"

# Start logic:
# start ALL when (core is down and platform is down)
# start platform when (core is up and platform is down)

# Start all if everything is stopped (not started yet)
- name: Start dashmate services
  ansible.builtin.command: "{{ dashmate_cmd }} start --verbose"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_start
  when:
    - not is_core_started
    - not is_platform_started
  changed_when: dashmate_start.rc == 0

# Start platform in case core is running
- name: Start dashmate platform services
  ansible.builtin.command: "{{ dashmate_cmd }} start --platform --verbose"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_start_platform
  when:
    - is_core_started
    - not is_platform_started
  changed_when: dashmate_start_platform.rc == 0

# Restart logic
# if any of platform images were updated => restart platform
# if core or sentinel images updated => restart all
# dashmate version is changed => restart all
# dashmate config is changed => restart all

- name: Restart dashmate services
  ansible.builtin.command: "{{ dashmate_cmd }} restart --verbose"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_restart
  when:
    - dashmate_start_platform.skipped and dashmate_start.skipped
    - is_core_images_updated or is_dashmate_package_changed or is_dashmate_config_changed
  changed_when: dashmate_restart.rc == 0

- name: Restart dashmate platform services
  ansible.builtin.command: "{{ dashmate_cmd }} restart --platform --verbose"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_restart_platform
  when:
    - not dashmate_start_platform.changed and not dashmate_start.changed and not dashmate_restart.changed
    - is_platform_images_updated
  changed_when: dashmate_restart_platform.rc == 0

- name: Disable dashmate helper build
  ansible.builtin.command: "{{ dashmate_cmd }} config set dashmate.helper.docker.build.enabled false"
  become: true
  become_user: dashmate
  register: build_dashmate_helper
  args:
    chdir: '{{ dashmate_cwd }}'
  changed_when: build_dashmate_helper.rc == 0

- name: Get service statuses
  ansible.builtin.command: "{{ dashmate_cmd }} status services --format=json"
  become: true
  become_user: dashmate
  changed_when: started_dashmate_services.rc == 0
  args:
    chdir: '{{ dashmate_cwd }}'
  register: started_dashmate_services
  when: mode == 'seed'

- name: Set facts
  ansible.builtin.set_fact:
    containers_to_stop: >-
      {{
        started_dashmate_services.stdout |
        from_json |
        json_query('[?service!=`dashmate_helper`&&service!=`core`&&service!=`drive_tenderdash`]') |
        map(attribute='containerId') |
        list
      }}
  when: mode == 'seed'

- name: Stop some services in seed mode
    community.docker.docker_container:
    name: "{{ item }}"
    state: stopped
  when: mode == 'seed'
  loop: "{{ containers_to_stop }}"

# TODO Convenient tasks until we have this functionality in dashmate
# - name: Replace parameters in tenderdash config
#  ansible.builtin.lineinfile:
#    path: /home/dashmate/.dashmate/testnet/platform/drive/tenderdash/config.toml
#    regexp: "^(# )?{{ item.parameter }} = .*$"
#    line: "{{ item.parameter }} = \"{{ item.value }}\""
#  loop:
#    # This field provides an unsafe override of the Propose timeout consensus parameter.
#    # This field configures how long the consensus engine will wait for a proposal block before prevoting nil.
#    # If this field is set to a value greater than 0, it will take effect.
#    # Default: 3s
#    - parameter: 'unsafe-propose-timeout-override'
#      value: '5s'
#
#    # This field provides an unsafe override of the ProposeDelta timeout consensus parameter.
#    # This field configures how much the propose timeout increases with each round.
#    # If this field is set to a value greater than 0, it will take effect.
#    # Default: 500ms
#    - parameter: 'unsafe-propose-timeout-delta-override'
#      value: '1000ms'
#
#    # This field provides an unsafe override of the Vote timeout consensus parameter.
#    # This field configures how long the consensus engine will wait after receiving +2/3 votes in a round.
#    # If this field is set to a value greater than 0, it will take effect.
#    # Default: 1s
#    - parameter: 'unsafe-vote-timeout-override'
#      value: '5s'
#
#    # This field provides an unsafe override of the VoteDelta timeout consensus parameter.
#    # This field configures how much the vote timeout increases with each round.
#    # If this field is set to a value greater than 0, it will take effect.
#    # Default: 500ms,
#    - parameter: 'unsafe-vote-timeout-delta-override'
#      value: '1000ms'
#
#    # This field provides an unsafe override of the Commit timeout consensus parameter.
#    # This field configures how long the consensus engine will wait after receiving +2/3 precommits before beginning the next height.
#    # If this field is set to a value greater than 0, it will take effect.
#    # Default: 1s
#    - parameter: 'unsafe-commit-timeout-override'
#      value: '3s'

# - name: Create and start services if needed
#  ansible.builtin.shell: |
#    LOCAL_UID=$(id -u) LOCAL_GID=$(id -g) \
#    docker compose --env-file {{ dashmate_home }}/.env \
#    up -d
#  become: true
#  become_user: dashmate
#  args:
#    chdir: /usr/lib/dashmate
#  register: dashmate_compose_command
#  changed_when: dashmate_compose_command.rc == 0

# - name: Restart platform services
#  ansible.builtin.shell: |
#    LOCAL_UID=$(id -u) LOCAL_GID=$(id -g) \
#    docker compose --env-file {{ dashmate_home }}/.env \
#    restart drive_abci drive_tenderdash dapi_api dapi_tx_filter_stream
#  become: true
#  become_user: dashmate
#  args:
#    chdir: /usr/lib/dashmate
#  register: dashmate_compose_command
#  changed_when: dashmate_compose_command.rc == 0
