---
- name: Set vars
  ansible.builtin.import_tasks: ./set_vars.yml

- name: Reindex dashmate node
  ansible.builtin.command: "{{ dashmate_cmd }} reindex -d --force"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_reset
  changed_when: dashmate_reset.rc == 0
