---

- name: Stop node
  ansible.builtin.command: yarn dashmate stop
  become: true
  become_user: dashmate
  ignore_errors: true
  args:
    chdir: '{{ dashmate_source_dir }}'
  register: dashmate_stop
  changed_when: dashmate_stop.rc == 0

- name: Reset platform
  ansible.builtin.command: yarn dashmate reset --platform-only --force
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_source_dir }}'
  register: dashmate_reset
  changed_when: dashmate_reset.rc == 0
