---

- name: Reset platform
  ansible.builtin.command: yarn dashmate reset --platform-only --force --hard
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_source_dir }}'
  register: dashmate_reset
  changed_when: dashmate_reset.rc == 0
