---

- name: Restart all dashmate services for current chunk
  ansible.builtin.command: "{{ dashmate_cmd }} restart --safe --verbose"
  become: true
  become_user: dashmate
  args:
    chdir: '{{ dashmate_cwd }}'
  register: dashmate_restart_all
  delegate_to: "{{ item }}"
  with_items: "{{ current_chunk }}"
#  environment:
#    ANSIBLE_ASYNC_DIR: "/home/dashmate/.ansible_async"
#
#- name: Wait for restart complete
#  async_status:
#    jid: "{{ item.ansible_job_id }}"
#  register: job_result
#  until: job_result.finished
#  retries: 30
#  delay: 10
#  with_items: "{{ dashmate_restart_all.results }}"
#  when: item.ansible_job_id is defined
#  delegate_to: localhost
#  run_once: true
#  environment:
#    ANSIBLE_ASYNC_DIR: "/home/dashmate/.ansible_async"

- name: Print progress
  debug:
    msg: "Restarted chunk {{ current_chunk_index + 1 }} of {{ host_chunks | length }}"

- name: Wait for delay before restarting next chunk
  pause:
    minutes: "{{ restart_delay_minutes }}"
  when: current_chunk_index + 1 < host_chunks|length
