---

- name: Set dashmate vars
  ansible.builtin.set_fact:
    dashmate_cmd: "{{ 'yarn dashmate' if dashmate_branch is defined else 'dashmate' }}"
    dashmate_cwd: "{{ dashmate_source_dir if dashmate_branch is defined else dashmate_home }}"
