---

- name: Reset platform (dashmate)
  ansible.builtin.import_role:
    name: dashmate
    tasks_from: destroy_platform
  when: inventory_hostname in groups["hp_masternodes"]

- name: Remove platform (seeds)
  community.docker.docker_compose:
    project_src: '{{ tenderdash_compose_path }}'
    state: absent
  when:
    - inventory_hostname not in groups["hp_masternodes"]

- name: Delete platform dir (seeds)
  ansible.builtin.file:
    state: absent
    path: '{{ tenderdash_compose_path }}'
  when:
    - inventory_hostname not in groups["hp_masternodes"]

- name: Remove any remaining docker data
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
