---

- name: Reset platform (dashmate)
  ansible.builtin.import_role:
    name: dashmate
    tasks_from: destroy_platform
  when: inventory_hostname in groups["hp_masternodes"] or inventory_hostname in groups["seeds"]

- name: Remove any remaining docker data
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
