version: '3'

services:
  ipfs:
    image: {{ ipfs_image }}
    command: daemon --enable-gc --migrate --enable-pubsub-experiment
    environment:
      LIBP2P_FORCE_PNET: 1
      SWARM_KEY: ${SWARM_KEY}
      SWARM_PEER: ${SWARM_PEER}
    ports:
      - 4001:4001
    volumes:
      - ipfs:/data/ipfs
      - {{ mn_evo_services_path }}/ipfs/init.sh:/usr/local/bin/start_ipfs

volumes:
  ipfs:
