---

- name: Create platform services dir
  ansible.builtin.file:
    path: '{{ mn_evo_services_path }}'
    state: directory
    recurse: true

- name: Create platform logs dir
  ansible.builtin.file:
    path: '{{ mn_evo_services_path }}/logs'
    state: directory
    recurse: true

- name: Configure log rotation
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_applications:
      - name: platform-logs
        definitions:
          - logs:
              - '{{ mn_evo_services_path }}/logs/*.log'
            options:
              - rotate 7
              - daily
              - maxsize 1G
              - missingok
              - notifempty
              - copytruncate
              - compress
              - delaycompress

- name: Ensure logrotate runs hourly under systemd timer
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/logrotate.timer
    regexp: '^OnCalendar=hourly'
    insertafter: '^OnCalendar=daily'
    line: OnCalendar=hourly

- name: Enable and restart logrotate systemd timer
  ansible.builtin.systemd:
    name: logrotate.timer
    state: restarted
    enabled: true
    daemon_reload: true

- name: Copy files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ mn_evo_services_path }}/{{ item }}'
    mode: 0644
  loop:
    - docker-compose.yml
    - dapi-nginx.conf
    - dapi-nginx-grpc.conf
    - dapi-nginx-errors.grpc_conf
    - .env
    - dapi-envoy.yaml

- name: Pull platform docker images
  community.docker.docker_compose:
    project_src: '{{ mn_evo_services_path }}'
    pull: true

- name: Configure Tendermint
  ansible.builtin.import_tasks: tendermint.yml
  vars:
    skip_genesis: "{{ skip_tenderdash_genesis | default(false) | bool }}"

- name: Start masternode evolution services
  community.docker.docker_compose:
    project_src: '{{ mn_evo_services_path }}'
    state: present
    restarted: true
    pull: true
