---

- name: Get blockchain info
  command: dash-cli getblockchaininfo
  register: getblockchaininfo_result
  changed_when: getblockchaininfo_result.stdout | to_json | length > 0

- name: Set initial and required variables
  set_fact:
    initial_block_count: '{{ (getblockchaininfo_result.stdout | from_json).blocks }}'
    required_block_count: 1

- name: Set required variables for devnets
  set_fact:
    required_block_count: 2
  when: dash_network == "devnet" # devnet has 2 genesis blocks

- name: Show initial block count
  debug:
    var: initial_block_count

- name: Generate first block
  command: 'dash-cli generatetoaddress 1 {{ miner_payment_address }}'
  when: initial_block_count|int < required_block_count|int
