---

- name: Destroy network
  hosts: all
  become: true
  roles:
    - role: kill_network
      when: target == "network"

- name: Destroy platform
  hosts: masternodes,seed_nodes
  become: true
  roles:
    - role: kill_platform
      when: target == "platform"
