- src: geerlingguy.pip
  version: 1.3.0

- src: geerlingguy.docker
  version: 2.5.3

- src: kyl191.openvpn

- src: Restless-ET.aws-scripts-mon

- src: arillso.logrotate

- src: elastic.beats
  version: v7.10.2

# - src: https://github.com/strophy/ansible-beats
