---

- name: Create certs and bundle dir
  file:
    path: '{{ bundle_path }}'
    state: directory
    recurse: true

- name: Generate templates for certificate creation
  template:
    src: 'certs/{{ item }}.j2'
    dest: '{{ bundle_path }}/{{ item }}'
    mode: 0644
  loop:
    - docker-compose.yml
    - instances.yml
    - .env
  notify: Generate certs
