version: '3'

services:
  sentinel:
    image: {{ sentinel_image }}
    container_name: sentinel
    restart: always
    environment:
      - DEBUG=false
      - RPCUSER={{ dashd_rpc_user }}
      - RPCPASSWORD={{ dashd_rpc_password }}
      - RPCHOST={{ private_ip }}
      - RPCPORT={{ dashd_rpc_port }}
      # Bypass scheduler
      - SENTINEL_ARGS=--bypass-scheduler
      - SENTINEL_DEBUG=1
