---
- name: Import Kibana GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: true

- name: Add Kibana repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
  become: true

- name: Install Kibana
  apt:
    name: kibana
    state: present
    update_cache: yes
  become: true

- name: Configure Kibana
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: Restart Kibana
  become: true

- name: Enable and start Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started
  become: true
