---

- name: get list of ProTx transactions from the wallet
  command: dash-cli protx list wallet true
  register: get_protx_list_result

- set_fact:
    registered_masternode_names: []

- name: get names of registered masternodes
  set_fact:
      registered_masternode_names: "{{ registered_masternode_names + [ item ] }}"
  when: get_protx_list_result.stdout|from_json|json_query("[?state.ownerAddress=='" + masternodes[item].owner.address + "']")
  with_items: '{{ groups["masternodes"] }}'

- name: determine new masternodes
  set_fact:
    new_masternode_names: "{{ groups['masternodes'] | difference(registered_masternode_names)}}"

- name: new masternodes list
  debug:
    var: new_masternode_names

- name: found collaterals for not inialized masternodes
  include_role:
    name: mn-fund-collateral
  vars:
    masternode_names: "{{ new_masternode_names }}"
  when: new_masternode_names|length > 0

- name: create pro tx for not initialzied masternodes
  include_role:
    name: mn-createprotx
  vars:
    masternode_names: "{{ new_masternode_names }}"
  when: new_masternode_names|length > 0
