---
# for development

# One of the following variables must be set
# dashmate_branch:   # install dashmate from a branch
# dashmate_version:  # install dashmate using a specific version

dashmate_config_dir: '{{ dashmate_home }}/.dashmate'
dashmate_source_dir: '{{ dashmate_home }}/platform'
dashmate_user: "dashmate"
dashmate_group: "dashmate"
dashmate_api_port: 9000
dashmate_platform_enable: true
dashmate_platform_dapi_envoy_ssl_provider: self-signed
dashmate_platform_dapi_envoy_ssl_provider_config_zerossl_api_key:
dashmate_platform_tenderdash_pprof_enable: false
dashmate_platform_dapi_envoy_http_connect_timeout: "0.5s"
dashmate_platform_dapi_envoy_http_response_timeout: "15s"
dashmate_platform_dapi_envoy_rate_limiter_enabled: true
dashmate_platform_drive_tenderdash_p2p_flush_throttle_timeout: "100ms"
dashmate_platform_drive_tenderdash_p2p_max_packet_msg_payload_size: 10240
dashmate_platform_drive_tenderdash_p2p_send_rate: 5120000
dashmate_platform_drive_tenderdash_p2p_recv_rate: 5120000
dashmate_platform_drive_tenderdash_mempool_size: 5000
dashmate_platform_drive_tenderdash_mempool_max_txs_bytes: 536870912 # 500Mb, default: 1073741824
dashmate_platform_drive_tenderdash_rpc_max_open_connections: 900
dashmate_platform_drive_tenderdash_consensus_peer_gossip_sleep_duration: "100ms"
dashmate_platform_drive_tenderdash_consensus_peer_query_maj23_sleep_duration: "2s"
# Unsafe params. Use only if you understand what you are doing.
dashmate_platform_drive_tenderdash_consensus_unsafe_override_propose_timeout:
dashmate_platform_drive_tenderdash_consensus_unsafe_override_propose_delta:
dashmate_platform_drive_tenderdash_consensus_unsafe_override_vote_timeout:
dashmate_platform_drive_tenderdash_consensus_unsafe_override_vote_delta:
