---

- name: import multifaucet donation address
  command: dash-cli {{ faucet_rpc_args }} importprivkey {{ faucet_privkey }}

- name: create multifaucet dirs
  file: path='{{ item }}' state=directory recurse=true
  with_items:
    - '{{ dashd_home }}/multifaucet/multifaucet'

- name: multifaucet config
  template:
    src: '{{ item }}'
    dest: '{{ dashd_home }}/multifaucet/{{ item }}'
  with_items:
    - docker-compose.yml
    - multifaucet/Dockerfile
    - multifaucet/db.conf.php
    - multifaucet/wallet.conf.php
    - multifaucet/faucet.conf.php
    - multifaucet/php.ini
    - init.sql

- name: multifaucet service
  docker_compose:
    project_src: '{{ dashd_home }}/multifaucet'
    state: present
    build: yes

- name: create promo codes table
  community.docker.docker_container_exec:
    container: multifaucet_db_1
    command: mysql -h localhost -D multifaucet -u multifaucet --password="multifaucet" -e 'CREATE TABLE IF NOT EXISTS faucet_promo_codes (id int NOT NULL, code varchar(255), minimum_payout int, maximum_payout int, PRIMARY KEY (id));'

- name: load promo codes
  community.docker.docker_container_exec:
    container: multifaucet_db_1
    command: mysql -h localhost -D multifaucet -u multifaucet --password="multifaucet" -e 'INSERT IGNORE INTO faucet_promo_codes (id,code,minimum_payout,maximum_payout) VALUES (1,"masternode",1000,1010);'
