---

- name: import multifaucet donation address
  command: dash-cli {{ faucet_rpc_args }} importprivkey {{ faucet_privkey }}

- name: create multifaucet dirs
  file: path='{{ item }}' state=directory recurse=true
  with_items:
    - /dash/multifaucet/multifaucet

- name: multifaucet config
  template:
    src: '{{ item }}'
    dest: '/dash/multifaucet/{{ item }}'
  with_items:
    - docker-compose.yml
    - multifaucet/Dockerfile
    - multifaucet/db.conf.php
    - multifaucet/wallet.conf.php
    - multifaucet/faucet.conf.php
    - multifaucet/php.ini
    - init.sql

- name: multifaucet service
  docker_service:
    project_src: /dash/multifaucet
    state: present
    build: yes
