---

- name: Create balance wallet
  ansible.builtin.command: 'dash-cli createwallet {{ balance_wallet }}'
  args:
    creates: "{{ dashd_home }}/.dashcore/{{ dash_network_name if dash_network == 'devnet' else 'testnet3' }}/wallets/{{ balance_wallet }}/wallet.dat"

- name: Create mno wallet
  ansible.builtin.command: 'dash-cli createwallet {{ mno_wallet }}'
  args:
    creates: "{{ dashd_home }}/.dashcore/{{ dash_network_name if dash_network == 'devnet' else 'testnet3' }}/wallets/{{ mno_wallet }}/wallet.dat"
