---

- name: Create dashd group
  ansible.builtin.group:
    name: '{{ dashd_group }}'

- name: Create dashd user
  ansible.builtin.user:
    name: '{{ dashd_user }}'
    comment: 'Dash user'
    group: '{{ dashd_group }}'
    home: '{{ dashd_home }}'
    create_home: true
    umask: '0002'
  register: dash_user

- name: Create .dashcore directory for each user
  ansible.builtin.file:
    path: '{{ item.dir }}/.dashcore'
    state: directory
    mode: 0755
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
  loop: '{{ users_to_manage }}'

- name: Write dash.conf file in /etc/
  ansible.builtin.template:
    src: dash.conf.j2
    dest: /etc/dash.conf
    owner: root
    group: root
    mode: 0644
  register: dash_config_state

- name: Symlink dash.conf to user dashcore directories to make rpc work
  ansible.builtin.file:
    path: '{{ item.dir }}/.dashcore/dash.conf'
    src: '/etc/dash.conf'
    state: link
    force: true
  loop: '{{ users_to_manage }}'

- name: Create dashcore docker-compose dir
  ansible.builtin.file:
    path: '{{ dashd_compose_path }}'
    state: directory
    mode: 0755
    recurse: true

- name: Copy dashcore docker-compose file
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ dashd_compose_path }}/{{ item }}'
    mode: 0644
  loop:
    - docker-compose.yml
    - .env

- name: Configure log rotation
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_use_hourly_rotation: true
    logrotate_applications:
      - name: core-logs
        definitions:
          - logs:
              - "{{ dashd_home }}/.dashcore/{{ dash_network_name if dash_network == 'devnet' else 'testnet3' }}/debug.log"
            options:
              - rotate 7
              - daily
              - maxsize 1G
              - missingok
              - notifempty
              - copytruncate
              - compress
              - delaycompress

- name: Set mode to logrotate cron file
  ansible.builtin.file:
    path: /etc/cron.daily/logrotate
    mode: "+x"

- name: Configure wallet
  ansible.builtin.import_tasks: wallet.yml
  become_user: '{{ dashd_user }}'
  when: enable_wallet is true

# TODO: why does this always take exactly 30 seconds on first deploy?
- name: Start dash core
  community.docker.docker_compose:
    project_src: '{{ dashd_compose_path }}'
    state: present
    restarted: true
    pull: true
    timeout: 30

- name: Wait for rpc to be available
  ansible.builtin.command: dash-cli getgovernanceinfo
  register: task_result
  until: task_result.rc == 0
  retries: 50
  delay: 2
  changed_when: task_result.rc == 0

- name: Import faucet privkey
  ansible.builtin.command: dash-cli -rpcwallet={{ wallet_rpc_wallet_faucet }} importprivkey {{ faucet_privkey }}
  register: result
  when: enable_wallet is true
  changed_when: result.rc == 0
