---

- name: Create dashd group
  group:
    name: '{{ dashd_group }}'

- name: Create dashd user
  user:
    name: '{{ dashd_user }}'
    comment: 'Dash user'
    group: '{{ dashd_group }}'
    home: '{{ dashd_home }}'
    create_home: yes
    umask: '0002'
  register: dash_user

- name: create .dashcore dir
  file: path={{ dashd_home }}/.dashcore state=directory mode='0750' owner='{{ dashd_user }}' group='{{ dashd_group }}'
- name: create .dashcore dir for root
  file: path=/root/.dashcore state=directory mode='0750' owner='root' group='root'

- name: Configure dashd
  template:
    src: 'dash.conf.j2'
    dest: '{{ dashd_home }}/.dashcore/dash.conf'
    owner: '{{ dashd_user }}'
    group: '{{ dashd_group }}'
    mode: '0640'
  register: dash_config_state

- name: copy configuration to root user dir to make rpc work
  shell: cp {{ dashd_home }}/.dashcore/dash.conf /root/.dashcore/

- name: create dashd container
  docker_container:
    name: dashd
    state: started
    restart: '{{ dash_config_state is changed }}'
    restart_policy: always
    image: '{{ dashd_evo_image if evo_services else dashd_image }}'
    pull: true
    user: '{{ dash_user.uid }}:{{ dash_user.group }}'
    working_dir: '{{ dashd_home }}'
    volumes:
    - '{{ dashd_home }}:/dash'
    network_mode: host
    command: 'dashd -conf={{ dashd_home }}/.dashcore/dash.conf -datadir={{ dashd_home }}/.dashcore'
    container_default_behavior: compatibility

- name: wait for rpc to be available
  shell: dash-cli getblockchaininfo
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 10
