---

- name: Create dashd group
  group:
    name: '{{ dashd_group }}'

- name: Create dashd user
  user:
    name: '{{ dashd_user }}'
    comment: 'Dash user'
    group: '{{ dashd_group }}'
    home: '{{ dashd_home }}'
    create_home: yes
    umask: '0002'
  register: dash_user

- name: create .dashcore directory for each user
  file:
    path: "{{ item.dir }}/.dashcore"
    state: "directory"
    mode: 0755
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  loop: "{{ users_to_manage }}"

- name: Configure dashd
  template:
    src: 'dash.conf.j2'
    dest: '{{ dashd_home }}/.dashcore/dash.conf'
    owner: '{{ dashd_user }}'
    group: '{{ dashd_group }}'
    mode: '0640'
  register: dash_config_state

- name: copy configuration to root user dir to make rpc work
  shell: cp {{ dashd_home }}/.dashcore/dash.conf /root/.dashcore/

- name: create dashd container
  docker_container:
    name: dashd
    state: started
    restart: '{{ dash_config_state is changed }}'
    restart_policy: always
    image: '{{ dashd_image }}'
    pull: true
    user: '{{ dash_user.uid }}:{{ dash_user.group }}'
    working_dir: '{{ dashd_home }}'
    volumes:
    - '{{ dashd_home }}:/dash'
    network_mode: host
    command: 'dashd -conf={{ dashd_home }}/.dashcore/dash.conf -datadir={{ dashd_home }}/.dashcore'
    container_default_behavior: compatibility

- name: wait for rpc to be available
  shell: dash-cli getblockchaininfo
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 10
