---

- name: disable pay-faucet
  systemd:
    name: 'pay-faucet'
    state: stopped
    enabled: False
  failed_when: False

- name: disable dashd-generate-miner
  systemd:
    name: 'dashd-generate-miner'
    state: stopped
    enabled: False
  failed_when: False

- name: stop all docker containers
  shell: if [ -n "$(docker container ls -a -q)" ]; then docker container stop $(docker container ls -a -q); fi

- name: remove all docker data
  shell: docker system prune -a -f --volumes

- name: Unmount data
  ansible.posix.mount:
    path: /dash/elastic/data
    state: unmounted
  when: inventory_hostname in groups['logs_nodes']

- name: delete dash home dir
  file:
      state: absent
      path: "{{ dashd_home }}/"