---

# Requires "masternode" and "masternode_name" variables

- name: Create ProUpServTx for {{ masternode_name ~ '/' ~ masternode.owner.address }}
  ansible.builtin.command: "dash-cli -rpcwallet={{ wallet_rpc_wallet_mno }} protx update_service
            {{ vars['protx_' + masternode_name | replace('-', '_')] }}
            {{ hostvars[masternode_name].public_ip }}:{{ dashd_port }}
            {{ masternode.operator.private_key }}
            ''
            {{ masternode.collateral.address }}" # Should already be funded from registration protx
  register: protx
  changed_when: protx.stdout | length == 64
  when: 'masternode_name is not match ("hp*")'

- name: Create ProUpServTx for {{ masternode_name ~ '/' ~ masternode.owner.address }}
  ansible.builtin.command: "dash-cli -rpcwallet={{ wallet_rpc_wallet_mno }} protx update_service_hpmn
            {{ vars['protx_' + masternode_name | replace('-', '_')] }}
            {{ hostvars[masternode_name].public_ip }}:{{ dashd_port }}
            {{ masternode.operator.private_key }}
            {{ masternode.node_key.id }}
            {{ tendermint_p2p_port }}
            {{ dapi_port }}
            ''
            {{ masternode.collateral.address }}" # Should already be funded from registration protx
  register: protx
  changed_when: protx.stdout | length == 64
  when: 'masternode_name is match ("hp*")'

- name: Add resulting txid to list
  ansible.builtin.set_fact:
    created_protx_list: "{{ created_protx_list + [ protx ] }}"
