---

# Requires "masternode" and "masternode_name" variables

- name: Create ProUpServTx for {{ masternode_name ~ '/' ~ masternode.owner.address }}
  ansible.builtin.command: "dash-cli -rpcwallet={{ wallet_rpc_wallet_mno }} protx update_service
            {{ vars['protx_' + masternode_name | replace('-', '_')] }}
            {{ hostvars[masternode_name].public_ip }}:{{ dashd_port }}
            {{ masternode.operator.private_key }}
            ''
            {{ fee_address.stdout }}" # Should already be funded from registration protx
  register: protx
  changed_when: protx.stdout | length == 64
