name: Package Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - v[0-9]+\.[0-9]+-dev
jobs:
  test:
    name: Test package
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
        with:
          path: ansible
